MONGODB_HOST: mongodb.shivaprasad.fun
REDIS_HOST: redis.shivaprasad.fun
CATALOGUE_HOST: catalogue.shivaprasad.fun
CART_HOST: cart.shivaprasad.fun
USER_HOST: user.shivaprasad.fun
RABBITMQ_HOST: rabbitmq.shivaprasad.fun
MYSQL_HOST: mysql.shivaprasad.fun
SHIPPING_HOST: shipping.shivaprasad.fun
PAYMENT_HOST: payment.shivaprasad.fun